### ISSUE TITLE
error  Expected linebreaks to be 'LF' but found 'CRLF'

### ISSUE THREAD

**Issue by bidon5** [micromata/bootstrap-kickstart#97]
[consoleLog.txt](https://github.com/micromata/bootstrap-kickstart/files/528945/consoleLog.txt)

Hi,
consoleLog File is attached.
It seems  to be a problem with:

http://eslint.org/docs/rules/linebreak-style

under Windows.

...
66:12  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  67:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  68:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  69:50  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  70:10  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  71:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  72:16  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  73:15  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  74:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  75:55  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
  76:4   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style

? 989 problems (989 errors, 0 warnings)

Warning: Task "eslint:check" failed. Use --force to continue.

Aborted due to warnings.
...

**Comment by mischah** [comment]
Hej, 

how have you installed bootstrap kickstart? 
via `git clone` of this repository or via `yo bootstrap-kickstart`?

Thanks, Michael

**Comment by mischah** [comment]
Possible fix:

Run the following command in your projects root:

```
grunt eslint:fix 
```

Can’t you tell your editor/IDE to use Linux linebreaks?
Like defined in our [.editorconfig](https://github.com/micromata/bootstrap-kickstart/blob/master/.editorconfig#L7) 

Is there an editorconfig plugin available for your editor/IDE? 
Check: http://editorconfig.org/#download

**Comment by bidon5** [comment]
Hi,
installed via git clone

greets Reto

**Comment by bidon5** [comment]
Nice,

grunt eslint:fix 
has solved it

Thanks
Reto

**Comment by mischah** [comment]
Its just a temporary fix as long as you still using windows linebreaks.

Explanation: ESLint is checking your JavaScript files for errors.
We are using this config which forces unix line breaks:
https://github.com/sindresorhus/eslint-config-xo/blob/master/index.js#L153

To fix that on a long term you need to apply one of the following fixes:

+ Make sure your editor uses unix linebreaks in this project
+ Override the ESLint linebreaks settings within the projects [.eslintrc](https://github.com/micromata/bootstrap-kickstart/blob/master/.eslintrc)
  + You could add use `'linebreak-style': ['error', 'windows'] ` to produce an error when someone uses other that windows linebreaks
  + You could use `'linebreak-style': ['warn', 'unix'] ` to produce an warning instead of an error.
  + You could disable that check with `'linebreak-style': 'off' `
    + Not recommend though

**Comment by mischah** [comment]
Closing this one. Feel free to contact me if you have additional questions 😘

**Comment by mischah** [comment]
Maybe @krnlde can give additional input how he handles linebreaks on windows.

**Comment by krnlde** [comment]
you could  configure your git to check out Linux style line endings instead of "check out windows style, commit Linux style". Never used that in practice though.
